### ISSUE TITLE
Buttons on Skyper launchpad page does not work.

### ISSUE THREAD

**Issue by chrhol** [Polyjuice/Skyper#2]
To reproduce:
1) Start Launcher and Skyper.
2) Goto http://localhost:8080
3) Click on the Skyper icon.
4) Click on any button (Add a friend for example)

The following error is shown in the browser console:
> Uncaught TypeError: Cannot set property 'FirstName$' of undefinedjson-patch-duplex.js:96 objOps.replacejson-patch-duplex.js:597 applypuppet.js:529 Puppet.validateAndApplySequencejson-patch-ot-agent.js:71 applyOTjson-patch-queue.js:66 JSONPatchQueue.receivepuppet.js:560 Puppet.handleRemoteChangepuppet.js:194 that._ws.onmessage

If the page is reloaded from this url (http://localhost:8080/launcher/workspace/Skyper) the buttons work again.

**Comment by warpech** [comment]
This is fixed now. Thx!
